
persistence:
  path: "../../rawdata/converted"

jwt:
  privKeyFile: "./zertifikat-key.pem"
  pubKeyFile: "./zertifikat-pub.pem"

mqtt:
  host: "tcp://eegfaktura-mosquitto:1883"
  id: "edash-energystore-1"
  qos: 1
#  energySubscriptionTopic: "eda/response/energy/+"
  energySubscriptionTopic: "eda/response/+/protocol/cr_msg"
  inverterSubscriptionTopic: "eda/response/+/protocol/inverter_msg"
services:
  mail-server: "localhost:9090"
